apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhotelwrk-wlgen
  namespace: blueprint-hotel-reservation
  labels:
    job: workload
spec:
  replicas: 1
  selector:
    matchLabels:
      job: workload
  template:
    metadata:
      labels:
        job: workload
    spec:
      restartPolicy: Always
      containers:
      - name: wlgen
        image: ghcr.io/sregym/blueprint-hotel:20260913-workload@sha256:873f718bb26bbe9568fc3b469aa6b1511e5cb70a602db4dc75f6db702d87cfac
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bhotelwrk-wlgen-env
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "🚀 Running wlgen_proc with FRONTEND_SERVICE_HTTP_DIAL_ADDR=$FRONTEND_SERVICE_HTTP_DIAL_ADDR and JAEGER_DIAL_ADDR=$JAEGER_DIAL_ADDR"
              /app/wlgen_proc --outfile $OUTFILE --duration $DURATION --tput $TPUT --multiplier $MULTIPLIER --stabletime $STABLETIME --triggertime $TRIGGERTIME --reverttime $REVERTTIME
            done
