apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
      convert
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    configmap: rpc
    io.kompose.service: user-service
  name: user-service

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
          convert
        kompose.image-pull-policy: IfNotPresent
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: user-service-container-env
        - configMapRef:
            name: rpc
        image: ghcr.io/sregym/blueprint-hotel:20260913-user@sha256:1a209c4dd50d5a851da719a33090d1a8733a168d27471f5b7deb338a2b02a357
        imagePullPolicy: IfNotPresent
        name: user-service-container
        ports:
        - containerPort: 12345
          protocol: TCP
      hostname: user-service
      restartPolicy: Always
