apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
      convert
    kompose.image-pull-policy: IfNotPresent
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    configmap: rpc
    io.kompose.service: geo-service
  name: geo-service

spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: geo-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-no-rpc.yml -o k8s-no-rpc/ -n blueprint-hotel
          convert
        kompose.image-pull-policy: IfNotPresent
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: geo-service
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: geo-service-container-env
        - configMapRef:
            name: rpc
        image: ghcr.io/sregym/blueprint-hotel:20260913-geo@sha256:2b511768f33cd50181eb68a941c91a01c85586dd9e069f5eee973163dfc904c2
        imagePullPolicy: IfNotPresent
        name: geo-service-container
        ports:
        - containerPort: 12345
          protocol: TCP
      hostname: geo-service
      restartPolicy: Always
