name: media-frontend

ports:
  - port: 8081
    targetPort: 8080

container:
  dockerRegistry: ghcr.io
  image: sregym/media-frontend
  imageVersion: sha-d2c036bc3d1138f5a0bdaffd3d87f37522c3461a@sha256:32de5e0371ccb7f47f36e1f027ae0075a7e265e4eed374c1b1020fe213754d00
  name: media-frontend
  ports: 
  - containerPort: 8081
  env:
  - name: fqdn_suffix
    value: ".{{ .Release.Namespace }}.svc.cluster.local"
  volumeMounts:
    - name: lua-scripts
      mountPath: /usr/local/openresty/nginx/lua-scripts

initContainer:
  dockerRegistry: ghcr.io/sregym
  image: social-network-assets
  imageVersion: v1
  name: alpine-container
  volumeMounts:
  - name: lua-scripts
    mountPath: /lua-scripts
  command: "/bin/sh" 
  args: ["-c", "cp -r /opt/social-network/media/lua-scripts/. /lua-scripts/"]

volumes:
  - name: lua-scripts

configMaps:
  - name: nginx.conf
    mountPath: /usr/local/openresty/nginx/conf/nginx.conf
    value: nginx

  - name: jaeger-config.yml
    mountPath: /social-network-microservices/config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /social-network-microservices/config/service-config.json
    value: service-config
